/**
 * Full-page background: the real Elbasan building-footprint data (public/
 * city-blueprint.svg, generated by scripts/build-city-blueprint.py from
 * public/data/buildings.geojson -- ~3100 real building outlines), used as a
 * faint citywide blueprint instead of an abstract pattern. Sits behind the
 * whole layout (see the `relative` + `-z-10` wiring in
 * CommandCenterClient); every panel is opaque, so this only shows through
 * the gaps, the translucent header, and the space below the sidebars.
 */
export default function AppBackground() {
  return (
    <div className="absolute inset-0 -z-10 overflow-hidden pointer-events-none" aria-hidden="true">
      <div className="absolute inset-0 bc-glow" />
      {/* eslint-disable-next-line @next/next/no-img-element -- a static SVG
          decorative background isn't a next/image optimization candidate */}
      <img
        src="/city-blueprint.svg"
        alt=""
        className="absolute inset-0 w-full h-full object-cover bc-city-blueprint"
      />
    </div>
  );
}
